### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by mohadel92** [foxdeep/owl_detection_camera#2]
Hi,
i tried several times to call OwlDetectionCamera.startDetection(); or to view OwlDetectionCamera as a widget 
but i couldn't load the view 
the docs of this package is very brief and doesn't include a valid example
any help?

**Comment by mohadel92** [comment]
E/MethodChannel#flutter/platform_views(27122): 	at com.strc_foxconn.owl_detection_camera.CameraView.<init>(CameraView.java:82)
E/MethodChannel#flutter/platform_views(27122): 	at com.strc_foxconn.owl_detection_camera.CameraFactory.create(CameraFactory.java:26)
E/MethodChannel#flutter/platform_views(27122): 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:230)
E/MethodChannel#flutter/platform_views(27122): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:122)
E/MethodChannel#flutter/platform_views(27122): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/MethodChannel#flutter/platform_views(27122): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)

**Comment by leechupe** [comment]
Hi mohadel92:
Could u give more information?
ex: 
Platform, OS version, and how u implement

Did u try example?

**Comment by leechupe** [comment]
Because there is no any other further information.
