### ISSUE TITLE
OwlDetectionCamera.onImageCallbacks = (name, path) didn't work

### ISSUE THREAD

**Issue by sardarmonsoorsait** [foxdeep/owl_detection_camera#3]
Hi,
all methods work perfecly except OwlDetectionCamera.onImageCallbacks = (name, path)  
no any error messages please give any solution to this issue

NB:  OwlDetectionCamera.onFaceRectangleCallback works perfectly ,i change  mIsDetectSuccess = true; this statement to this method condition workscorrectly but  didn't get the image and path

**Comment by leechupe** [comment]
HI sardarmonsoors:

Please tell me more information:

Didn't you receive any string from the OwlDetectionCamera.onImageCallbacks functions' callback value? likes: name or path.

Which platform were you running it with?  Android or IOS?

Did you grant every permissions?

**Comment by sardarmonsoorsait** [comment]
Thanks for your response that onImagecallbacks didnot execute

**Comment by sardarmonsoorsait** [comment]
1.    OwlDetectionCamera.onImageCallbacks = (name, path) {
     
      if (!mIsDetectSuccess) {
        mImagePath = path;
        mIsDetectSuccess = true;
        setState(() {});
      }
    };
this callback didn't execute when the app is run but when the face detected,this call back execute successfully=>  OwlDetectionCamera.onFaceRectangleCallback = (Rect aValue) {
      if (!mIsDetectSuccess) {
       

        mIsDetectSuccess = true;     // i add this line
        print('lllllllllllllllllllllllllllllllllllllllllll$mIsDetectSuccess');  // i add this line 
        setState(() {});
      }
      print("Face Rectangle :$aValue");
    };


2 . I grant all three permissions.

3. I am running on android

**Comment by leechupe** [comment]
> 1. OwlDetectionCamera.onImageCallbacks = (name, path) {
>    if (!mIsDetectSuccess) {
>    mImagePath = path;
>    mIsDetectSuccess = true;
>    setState(() {});
>    }
>    };
>    this callback didn't execute when the app is run but when the face detected,this call back execute successfully=>  OwlDetectionCamera.onFaceRectangleCallback = (Rect aValue) {
>    if (!mIsDetectSuccess) {
>    mIsDetectSuccess = true;     // i add this line
>    print('lllllllllllllllllllllllllllllllllllllllllll$mIsDetectSuccess');  // i add this line
>    setState(() {});
>    }
>    print("Face Rectangle :$aValue");
>    };
> 
> 2 . I grant all three permissions.
> 
> 3. I am running on android
____________________________________

Hi sardarmonsoors:

I have published the v0.1.8 version yesterday.

Could you update the lib version first and check if the Flutter SDK is 2.17.6 ?

If the problem still exists, please let me know. 

Thank you.

**Comment by leechupe** [comment]
Because there is no other further information, close it.

**Comment by alejandrogiubel** [comment]
Hi. I have same issue. onImageCallbacks do nothing. Any idea?

**Comment by leechupe** [comment]
Hi Alejandrogiubel:

I published the v0.2.6 version recently and updated the example.

After seeing the example, the problem still exists. Please let me know.

Thank you.

**Comment by leechupe** [comment]
> Hi. I have same issue. onImageCallbacks do nothing. Any idea?

Hi Alejandrogiubel:

I published the v0.2.6 version recently and updated the example.

After seeing the example, the problem still exists. Please let me know.

Thank you.
